name: C++ SDL Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SDL2 dependencies
      run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

    - name: Compile C++ code
      run: g++ -o output_file Algo.cpp -lSDL2

    - name: Run executable
      run: ./output_file
